# Generated by Django 5.0.6 on 2024-06-14 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_monthlyearning_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyearning',
            unique_together={('user', 'month')},
        ),
    ]
